spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: authuser
    password: authpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationThatNeedsToBeVeryLongForSecurity
    access-token:
      expiration: 1800000  # 30분 (milliseconds)
    refresh-token:
      expiration: 1209600000  # 2주 (milliseconds)

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/auth/callback/kakao
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/auth/callback/naver
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/auth/callback/google

logging:
  level:
    com.dd3ok.authservice: DEBUG
    org.springframework.security: DEBUG